In [3]:
#importing libraries

import pandas as pd
import numpy as np
import pandas_profiling
#Import TfIdfVectorizer from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer

#Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
tfidf = TfidfVectorizer(stop_words='english')

In [4]:
#loading  and copying post data

post_data = pd.read_csv('posts.csv')
post_data2 = post_data.copy()
post_data2.head(5)

,id,user_id,title,content,tags,slug,created_at,updated_at,image,status_id,action,post_id
0,1,2077,What i have learnt so far on HTML,I learnt how to use the table tag as i have us...,NaN,what-i-have-learnt-so-far-on-html-985,8/25/2019 19:39,8/28/2019 11:30,1,NaN,NaN,NaN
1,2,1719,HTML BEGINS HERE,"I am on this journey with start.ng, and here ...",Technology,html-begins-here-4d6,8/25/2019 19:44,8/28/2019 11:30,1,NaN,NaN,NaN
2,4,1310,My Laziness In The Open,I have not been attending classes on the HNG c...,NaN,my-laziness-in-the-open-029,8/25/2019 19:50,8/28/2019 11:30,1,NaN,NaN,NaN
3,6,1787,MY TASK 2,My journey on **StartNG** pre-internship progr...,NaN,my-task-2-649,8/25/2019 19:51,8/28/2019 11:30,1,NaN,NaN,NaN
4,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",NaN,task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,1,NaN,NaN,NaN

In [5]:
#understanding data

post_data2.dtypes

id              int64
user_id         int64
title          object
content        object
tags           object
slug           object
created_at     object
updated_at     object
image          object
status_id     float64
action         object
post_id       float64
dtype: object

In [6]:
#Loading and copying user data

user_data = pd.read_csv('users.csv')

user_data2 = user_data.copy()
user_data2.head(5)

,user_id,name,username,email,image,provider,provider_id,password,remember_token,created_at,updated_at,short_bio
0,1,Eniayomi Oluwaseyi,eniayomi,oluwaseyieniayomi@gmail.com,/storage/oluwaseyieniayomi/images//5lxMjdbOVca...,google,1.010000e+20,NaN,79kIhqDiWzqx1i3eFpGMpxfLdPVIvSfv8A3vN2PNEl4ig9...,8/1/2019 17:57,8/1/2019 17:57,Software Developer | DevOPs Engineer
1,2,Elijah Okokon,DMatrix,okoelijah@gmail.com,/storage/2/images//DB7axhFJpFUzPuCNPRMQ6X1iNwb...,google,1.060000e+20,NaN,Rz08FtDtdyAp8Cm5XJq5XumgZhEqytSu5MxxyHZYlHBhd0...,8/1/2019 18:05,8/1/2019 18:05,Web Developer
2,3,Jeffrey Ogah,jeff.ogah,jeff.ogah@gmail.com,https://lh3.googleusercontent.com/-FQgpN5l_UoY...,google,1.010000e+20,NaN,ZxNMYG05B6RQuSWaJlqlc8bGbPyFxNGNnNf5D86biFix4G...,8/1/2019 20:55,8/1/2019 20:55,Front End Developer | React Developer | Mentor...
3,4,Oluwaseyi Oluwapelumi,nathan,nathanoluwaseyi@gmail.com,/storage/4/images/thumbnail/TLWSEBK7C-UMECCGUP...,google,1.070000e+20,NaN,uxbOXr4Cw8tJyilWDKQRhi7TjiV7gBzjMnX0cb4i3ndFu6...,8/2/2019 16:52,8/2/2019 16:52,| Software Developer | DevOps Engineer | @linu...
4,5,PoRH,lamar,paulchibiukeigweze@gmail.com,/storage/5/images/thumbnail/images (2)_small_1...,google,1.030000e+20,NaN,EeCB77oXHo3zdZgYTVhWlw2EyHkTtLSJb2PjWFF9RuG7H1...,8/3/2019 11:33,8/3/2019 11:33,I Am lamar and you don't think am real?

In [7]:
user_data2.dtypes

user_id             int64
name               object
username           object
email              object
image              object
provider           object
provider_id       float64
password          float64
remember_token     object
created_at         object
updated_at         object
short_bio          object
dtype: object

In [8]:
#merging user and post data on user_id

df = pd.merge(post_data2, user_data2, on='user_id')

In [9]:
#copying merged data

metadata = df.copy()

df.head(5)

,id,user_id,title,content,tags,slug,created_at_x,updated_at_x,image_x,status_id,...,username,email,image_y,provider,provider_id,password,remember_token,created_at_y,updated_at_y,short_bio
0,1,2077,What i have learnt so far on HTML,I learnt how to use the table tag as i have us...,NaN,what-i-have-learnt-so-far-on-html-985,8/25/2019 19:39,8/28/2019 11:30,1,NaN,...,obiako4u53,obiako4u53@gmail.com,https://lh3.googleusercontent.com/-Gnb2o4SA6HU...,google,1.090000e+20,NaN,TitXROeUlC4a4c9VVpaIhfbAu5dPWVC2PrN5lLufalPFbx...,8/20/2019 22:28,8/20/2019 22:28,I am a person of Growth mindset. I believe i c...
1,2,1719,HTML BEGINS HERE,"I am on this journey with start.ng, and here ...",Technology,html-begins-here-4d6,8/25/2019 19:44,8/28/2019 11:30,1,NaN,...,kolawolejohn,kolawole.oajohn@gmail.com,/storage/kolawolejohn/images//h3OofJbAD9cW5Ro9...,google,1.130000e+20,NaN,GeEAAszJ1jjHBXZWwv0ujB1arkHJVMDveiRZSCSfRV4e0Q...,8/19/2019 21:42,8/19/2019 21:42,"I am Kolawole Adebayo Ogunfowokan, I am a trai..."
2,4,1310,My Laziness In The Open,I have not been attending classes on the HNG c...,NaN,my-laziness-in-the-open-029,8/25/2019 19:50,8/28/2019 11:30,1,NaN,...,Oladele,makanjuolaoladele@gmail.com,/storage/Oladele/images//irm5vHnrgL2XD3bvmhZR5...,google,1.140000e+20,NaN,ArBKC0Ons7Xy3G8llXn6MqcwiDKZxOFPibMlzzY1Lau4Yk...,8/19/2019 12:31,8/19/2019 12:31,Front-End enthusiast
3,6,1787,MY TASK 2,My journey on **StartNG** pre-internship progr...,NaN,my-task-2-649,8/25/2019 19:51,8/28/2019 11:30,1,NaN,...,emmanuel.ulaka16,emmanuel.ulaka16@gmail.com,/storage/1787/images//8RueyRdHpIdJdBZ5I7DWpU7i...,google,1.100000e+20,NaN,B56rhxElOxeJ1BPqj3qJsVz6TzVuc5S6hrOKlpQ1L1fgfr...,8/20/2019 0:45,8/20/2019 0:45,NaN
4,11,1787,MY TASK 2,My journey on **StartNG** pre-internship progr...,html,my-task-2-649,8/25/2019 19:57,8/28/2019 11:30,1,NaN,...,emmanuel.ulaka16,emmanuel.ulaka16@gmail.com,/storage/1787/images//8RueyRdHpIdJdBZ5I7DWpU7i...,google,1.100000e+20,NaN,B56rhxElOxeJ1BPqj3qJsVz6TzVuc5S6hrOKlpQ1L1fgfr...,8/20/2019 0:45,8/20/2019 0:45,NaN

In [10]:
metadata.dtypes

id                  int64
user_id             int64
title              object
content            object
tags               object
slug               object
created_at_x       object
updated_at_x       object
image_x            object
status_id         float64
action             object
post_id           float64
name               object
username           object
email              object
image_y            object
provider           object
provider_id       float64
password          float64
remember_token     object
created_at_y       object
updated_at_y       object
short_bio          object
dtype: object

In [11]:
metadata.shape

(876, 23)

In [12]:
metadata.describe()

                id      user_id  status_id  post_id   provider_id  password
count   876.000000   876.000000        0.0      0.0  8.760000e+02       0.0
mean    516.808219  1061.639269        NaN      NaN  1.088744e+20       NaN
std     278.648058   788.070779        NaN      NaN  5.313937e+18       NaN
min       1.000000     1.000000        NaN      NaN  1.000000e+20       NaN
25%     278.750000   338.000000        NaN      NaN  1.040000e+20       NaN
50%     523.500000   944.000000        NaN      NaN  1.090000e+20       NaN
75%     754.250000  1836.250000        NaN      NaN  1.130000e+20       NaN
max    1007.000000  2297.000000        NaN      NaN  1.180000e+20       NaN

In [13]:
#data with missing columns

metadata.isnull().sum()

id                  0
user_id             0
title               0
content             0
tags              694
slug                0
created_at_x        0
updated_at_x        0
image_x           476
status_id         876
action            871
post_id           876
name                0
username            0
email               0
image_y             0
provider            0
provider_id         0
password          876
remember_token      0
created_at_y        0
updated_at_y        0
short_bio         246
dtype: int64

In [14]:
#dropping missing columns

metadata.dropna(axis=1, inplace=True)

In [15]:
metadata.isnull().sum()

id                0
user_id           0
title             0
content           0
slug              0
created_at_x      0
updated_at_x      0
name              0
username          0
email             0
image_y           0
provider          0
provider_id       0
remember_token    0
created_at_y      0
updated_at_y      0
dtype: int64

In [16]:
metadata.describe()

                id      user_id   provider_id
count   876.000000   876.000000  8.760000e+02
mean    516.808219  1061.639269  1.088744e+20
std     278.648058   788.070779  5.313937e+18
min       1.000000     1.000000  1.000000e+20
25%     278.750000   338.000000  1.040000e+20
50%     523.500000   944.000000  1.090000e+20
75%     754.250000  1836.250000  1.130000e+20
max    1007.000000  2297.000000  1.180000e+20

In [17]:
pandas_profiling.ProfileReport(metadata)

In [18]:
#finding correlation

metadata.corr(method = 'pearson')

                   id   user_id  provider_id
id           1.000000 -0.165137    -0.095062
user_id     -0.165137  1.000000     0.096054
provider_id -0.095062  0.096054     1.000000

In [19]:
#finding correlation

metadata.corr(method = 'kendall')

                   id   user_id  provider_id
id           1.000000 -0.104611    -0.069794
user_id     -0.104611  1.000000     0.084080
provider_id -0.069794  0.084080     1.000000

In [20]:
import seaborn as sb
import matplotlib.pyplot as plt
metadata.columns

Index(['id', 'user_id', 'title', 'content', 'slug', 'created_at_x',
       'updated_at_x', 'name', 'username', 'email', 'image_y', 'provider',
       'provider_id', 'remember_token', 'created_at_y', 'updated_at_y'],
      dtype='object')

In [21]:
#Getting the TF-IDF score or frequency of a word occurring in a document, i.e the title

tfidf_matrix = tfidf.fit_transform(metadata['content'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

(876, 5122)

In [22]:
#compute users similarity score using the cosine similarity
# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [23]:
#defining a function that takes in a post title as an input and outputs a list of the 10 most similar post.Firstly, for this, you need a reverse mapping of movie titles and DataFrame indices. In other words, you need a mechanism to identify the index of a movie in your metadata DataFrame, given its title.


#Construct a reverse map of indices and movie titles
indices = pd.Series(metadata.index, index=metadata['title']).drop_duplicates()

#Get the index of the post given its title.

#Get the list of cosine similarity scores for that particular post with all posts. Convert it into a list of tuples where the first element is its position and the second is the similarity score.


#Sort the aforementioned list of tuples based on the similarity scores; that is, the second element.

#Get the top 10 elements of this list. Ignore the first element as it refers to self (the post most similar to a particular post is the post itself).

#Return the titles corresponding to the indices of the top elements.

In [24]:
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return metadata['title'].iloc[movie_indices]
get_recommendations('What i have learnt so far on HTML')

265                              third
308            WHAT I'VE LEARNT SO FAR
775                             TASK 2
776                             TASK 2
141                      CV Using html
261                               TEst
237           Startng task 2 Completed
28     WHAT I HAVE DONE SO FAR ON HTML
16                  What I done so far
51        Lucid post to start.ng Task1
Name: title, dtype: object

In [25]:
get_recommendations('Welcome to Lucid')

571                    pre- intership on startng
590                                        ochem
464                      my 2nd task on start.ng
465                      my 2nd task on start.ng
615                                My First Post
582                               Test an image.
449         Converting Cv to Html StartNg Task 2
502                      Journey round the world
504                               Journey so far
574    THE SKY IS MY STEPPING STONE WITH STARTNG
Name: title, dtype: object

In [26]:
metadata.title

0                      What i have learnt so far on HTML
1                                       HTML BEGINS HERE
2                                My Laziness In The Open
3                                              MY TASK 2
4                                              MY TASK 2
5                                                 Task 2
6                                Daily Log - CLASS DAY 1
7                                     My Journey on HTML
8                                            Please note
9                                     My Journey on HTML
10                                    My learning so far
11                               StartNG HTML Exposition
12                                     StartNG HTML task
13                             On StartNG Pre-Internship
14                                                   why
15                         HNG internship journey so far
16                                    What I done so far
17                             Learnt Learn and Learning
18                      How far we can go with just HTML
19                   Learning Web development at StartNg
20     The Journey with StartNG: Creating my CV with ...
21     The Journey with StartNG: Creating my CV with ...
22                                    The Journey So Far
23                                    The Journey So Far
24                                    The Journey So Far
25                   What i have done so far on start.ng
26                                         Task Number 7
27                          What has been learnt so far?
28                       WHAT I HAVE DONE SO FAR ON HTML
29                                                TASK 2
                             ...
846                           software testing for lucid
847                                      My html project
848                                      My html project
849                                    My Start.ng story
850    Overcoming the Rough Road to Front End Develop...
851    We Finally Have a Carbon-dioxide-filled Market...
852     How Not to Miss Important Information on StartNG
853                  User Acceptance Testing Using Lucid
854                                 HNGInternship6 Rules
855                                        StartNG Class
856                                   MY HTML EXPERIENCE
857                           ELLA'S START-NG EXPERIENCE
858                                           Post title
859                                            html test
860                  YOUR HIGH IQ WILL KILL YOUR STARTUP
861    A CHINESE VILLAGER WHO SELLS MORE SOFTWARE DAI...
862                BUILD AROUND YOUR DISCOVERY MECHANISM
863                      DON'T ASK WHY YOU WERE REJECTED
864                                        THE SUNFLOWER
865                                     Welcome to Lucid
866                                        This is lucid
867                                  this is a test post
868                                         this is mine
869                                 Your face PHP script
870                                         with picture
871                                 Post with two images
872                                                 asda
873                                       Speed Of Light
874                                                Am ok
875                                            jbhjkhkbb
Name: title, Length: 876, dtype: object

In [27]:
metadata.shape

(876, 16)

In [32]:
#uploading the following data
following_data = pd.read_csv('following.csv')

following_data.head()

   user_id  follower_id  status
0        3            6       1
1        6            3       1
2        3            2       1
3        3            7       1
4        7            2       1

In [33]:
following_data.describe()

           user_id  follower_id       status
count  5296.000000  5296.000000  5296.000000
mean    793.865370   695.724887     0.976020
std     518.974621   520.907520     0.153002
min       1.000000     1.000000     0.000000
25%     353.000000   218.000000     1.000000
50%     722.000000   642.000000     1.000000
75%    1161.000000  1075.000000     1.000000
max    2287.000000  2218.000000     1.000000

In [34]:
#merging metadata and following_data

df2 = pd.merge(metadata, following_data, on='user_id')

In [37]:
df2.isnull().sum()

id                0
user_id           0
title             0
content           0
slug              0
created_at_x      0
updated_at_x      0
name              0
username          0
email             0
image_y           0
provider          0
provider_id       0
remember_token    0
created_at_y      0
updated_at_y      0
follower_id       0
status            0
dtype: int64

In [38]:
df2.shape

(4099, 18)

In [39]:
#copying df2 

metadata2 = df2.copy()

In [41]:
metadata2.head(5)

,id,user_id,title,content,slug,created_at_x,updated_at_x,name,username,email,image_y,provider,provider_id,remember_token,created_at_y,updated_at_y,follower_id,status
0,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,Idongesit Essien,idongesitessien,ceoidessien7@gmail.com,/storage/idongesitessien/images//LmQIohc93loeh...,google,1.100000e+20,IQcHdoYWw51zMM3il8dypFQJbabDtX44smofDYDAd64qtf...,8/18/2019 21:58,8/18/2019 21:58,290,1
1,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,Idongesit Essien,idongesitessien,ceoidessien7@gmail.com,/storage/idongesitessien/images//LmQIohc93loeh...,google,1.100000e+20,IQcHdoYWw51zMM3il8dypFQJbabDtX44smofDYDAd64qtf...,8/18/2019 21:58,8/18/2019 21:58,1235,1
2,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,Idongesit Essien,idongesitessien,ceoidessien7@gmail.com,/storage/idongesitessien/images//LmQIohc93loeh...,google,1.100000e+20,IQcHdoYWw51zMM3il8dypFQJbabDtX44smofDYDAd64qtf...,8/18/2019 21:58,8/18/2019 21:58,107,1
3,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,Idongesit Essien,idongesitessien,ceoidessien7@gmail.com,/storage/idongesitessien/images//LmQIohc93loeh...,google,1.100000e+20,IQcHdoYWw51zMM3il8dypFQJbabDtX44smofDYDAd64qtf...,8/18/2019 21:58,8/18/2019 21:58,101,1
4,7,167,Task 2,"A Summary on The “idongesit.html” CV, Its Str...",task-2-7e5,8/25/2019 19:51,8/28/2019 11:30,Idongesit Essien,idongesitessien,ceoidessien7@gmail.com,/storage/idongesitessien/images//LmQIohc93loeh...,google,1.100000e+20,IQcHdoYWw51zMM3il8dypFQJbabDtX44smofDYDAd64qtf...,8/18/2019 21:58,8/18/2019 21:58,7,1

In [42]:
metadata2.columns

Index(['id', 'user_id', 'title', 'content', 'slug', 'created_at_x',
       'updated_at_x', 'name', 'username', 'email', 'image_y', 'provider',
       'provider_id', 'remember_token', 'created_at_y', 'updated_at_y',
       'follower_id', 'status'],
      dtype='object')

In [52]:
# Parse the stringified features into their corresponding python objects
from ast import literal_eval

metadata2['username'] = metadata2['username'].apply(literal_eval)

ValueError: malformed node or string: <_ast.Name object at 0x000001B247D471D0>

In [45]:
#adding more metadata

def create_soup(x):
    return ' '.join(x['username'])

In [49]:
# Create a new soup feature
metadata2['soup'] = metadata.apply(create_soup, axis=1)

In [50]:
# Import CountVectorizer and create the count matrix
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(metadata2['soup'])
# Compute the Cosine Similarity matrix based on the count_matrix
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

# Reset index of your main DataFrame and construct reverse mapping as before
metadata2 = metadata2.reset_index()
indices = pd.Series(metadata.index, index=metadata['content'])

ValueError: np.nan is an invalid document, expected byte or unicode string.